# Generated by Django 6.0.2 on 2026-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipient_extra_data_alter_recipient_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_user', models.EmailField(max_length=254)),
                ('email_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
            ],
        ),
    ]
